BUNDLE = "Bundle"
ORGANIZATION = "Organization"
INSURANCE_PLAN = "InsurancePlan"

BUNDLE_TYPE_COLLECTION = "collection"
LANGUAGE_EN_IN = "en-IN"
TELECOM_SYSTEM_PHONE = "phone"
TELECOM_SYSTEM_EMAIL = "email"
TELECOM_SYSTEM_URL = "url"
IDENTIFIER_USE_OFFICIAL = "official"
SYS_IDENTIFIER = "http://code.workz.com"
SYS_IRDAI_IDENTIFIER = "https://www.irdai.gov.in/identifier/tpa"
SYS_INSURER_IDENTIFIER = "https://www.irdai.gov.in/identifier/insurer"
CONTACT_PURPOSE_SYSTEM = "http://terminology.hl7.org/CodeSystem/contactentity-type"
SYS_SNOMED = "http://snomed.info/sct"

_ABDM_BASE = "https://nrces.in/ndhm/fhir/r4"

VS_INSURANCE_PLAN_TYPE = f"{_ABDM_BASE}/ValueSet/ndhm-insuranceplan-type"
VS_PLAN_TYPE = f"{_ABDM_BASE}/ValueSet/ndhm-plan-type"
VS_COST_APPLICABILITY = "http://hl7.org/fhir/ValueSet/insuranceplan-applicability"
APPLICABILITY_IN_NETWORK = "in-network"
APPLICABILITY_OUT_OF_NETWORK = "out-of-network"
APPLICABILITY_OTHER = "other"

EXT_SUPPORTING_INFO_REQ = f"{_ABDM_BASE}/StructureDefinition/Claim-SupportingInfoRequirement"
EXT_EXCLUSION = f"{_ABDM_BASE}/StructureDefinition/Claim-Exclusion"
EXT_CONDITION = f"{_ABDM_BASE}/StructureDefinition/Claim-Condition"
EXT_NETWORK = f"{_ABDM_BASE}/StructureDefinition/InsurancePlan-Network"

META_PROFILE_INSURANCE_PLAN = f"{_ABDM_BASE}/StructureDefinition/InsurancePlan"
META_PROFILE_ORGANIZATION = f"{_ABDM_BASE}/StructureDefinition/Organization"
META_PROFILE_DOCUMENT_BUNDLE = f"{_ABDM_BASE}/StructureDefinition/DocumentBundle"
META_PROFILE_INSURANCE_PLAN_BUNDLE = f"{_ABDM_BASE}/StructureDefinition/InsurancePlanBundle"